# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers: 
  - tifabio
  - yagobrandao
  - padupe
  - archaic10
  - BiancaZO
  - mauriciobernert
  - lucasvillatore
  - ymussi
  - GuilhermeMLS
  - PedroFellipe
numberOfReviewers: 4