version: 1.0.0
name: "Gandora"
jobs:
  - name: validation
    path: ./github/workflows/main.yaml
    uses: action | bot

  - name: pre-build
    path: ./github/workflows/main.yaml
    uses: action | null

  - name: build
    path: ./github/workflows/main.yaml
    uses: action | null

  - name: checagem estatica
    path: ./github/workflows/main.yaml
    uses: action | null

  - name: quality gateway
    path: ./github/workflows/main.yaml
    uses: action | null

  - name: testes
    path: ./github/workflows/main.yaml
    uses: action | null

  - name: coverage
    path: ./github/workflows/main.yaml
    uses: action | null

  - name: gmud
    path: ./github/workflows/main.yaml
    uses: action | bot
tags:
  - <linguaguens>
  - <infraestrutura>
