name: auto-changelog-cli
on:
  push:
    branches:
      - feature/ci

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: changelog
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: dependencys
        run: npm install

      - name: install auto-changelog
        run: npm install auto-changelog --save-dev

      - name: generate changelog
        run: npm run auto-changelog -p
      
      - name: write changelog on CHANGELOG.md
        run: echo "${{ steps.release.outputs.changelog }}"  >> CHANGELOG.md
        
      - name: Commit CHANGELOG.md
        run: |
          git config --local user.email ${{ secrets.c }}
          git config --local user.name ${{ secrets.MY_USER }}
          git add .
          git commit -m "ci: generate changelog"
      - name: Push changelog
        uses: ad-m/github-push-action@master
        with:
          branch: feature/ci
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true