name: Changelog
on: 
  push:
  
jobs:
  changelog:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: changelog
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: dependencys
        run: npm install
        
      - name: setting git
        run: |
          git config --local user.email ${{ secrets.MAIL_CI_GITHUB }}
          git config --local user.name ${{ secrets.USER_CI_GITHUB }}            
      
      - name: update version
        run: npm version patch
        
      - name: install auto-changelog
        run: npm install auto-changelog --save-dev

      - name: generate changelog
        run: npm auto-changelog -p
      
      - name: write changelog on CHANGELOG.md
        run: echo "${{ steps.release.outputs.changelog }}"  >> CHANGELOG.md
        
      - name: Commit CHANGELOG.md
        run: |          
          git add .
          git commit -m "ci: generate changelog"
      - name: Push changelog
        uses: ad-m/github-push-action@master
        with:
          branch: feature/ci
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          
          
