name: Node.js CI
on: 
  push:
    

jobs:
  build:
    name: Npm install & build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present

  checkLint:
    needs: build
    name: Npm checkLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install && npm run lint


  teste-unitario: 
    needs: checkLint
    name: Npm unitary test
    runs-on: ubuntu-latest
    environment: unit_test
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install && npm run test 
    
  coverage: 
    needs: teste-unitario
    name: Npm coverage
    runs-on: ubuntu-latest
    environment: coverage
    steps:
    - uses: actions/checkout@v2
    - run: npm install && npm run test:cov
