name: GMUD

on:
  pull_request:
    branches:
      - feature/create-gmud
 
jobs:
      
  check-title-pull-request:
    runs-on: ubuntu-latest
    name: 'check-title-pull-request' 
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "${{ github.event.pull_request.title }}"
