name: GMUD

on:
  pull_request:
    branches:
      - feature/create-gmud
 
jobs:
  check-status-service-desk:
    runs-on: ubuntu-latest
    name: check status service desk
    steps:
      - name: 'Create GMUD'
        id: res
        run: |
          data=$(curl --location --request POST 'http://kong-wallarm.redekasa.com/slifer/v1/gmud' \
          --header "Authorization: ${{ secrets.BASIC_AUTH_JIRA }}" \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "serviceDeskId": "31",
              "requestTypeId": "538",
              "id_card_issue": "SRE-417",
              "summary": "summary teste4",
              "description": "description teste4",
              "service": [{"id" : "ari:cloud:graph::service/e27f7002-0a2f-11eb-98e1-0a77f3f45304/907c246a-0f3a-11ec-8fa8-0abe3f4a6601"}],
              "tecnical_approval": "adolfo.pereira@madeiramadeira.com.br",
              "business_approval": "bruno.oliveira@madeiramadeira.com.br"

          }
          ' | jq -r '.data._links.web')                 
      - name: 'GET STATUS GMUD'
        run: | 
          echo "$data"
