name: GMUD

on:
  pull_request:
    branches:
      - feature/create-gmud
 
jobs:
  check-existence-jira-issue:
    runs-on: ubuntu-latest
    name: 'Check the jira for an issue'
    steps:
      - name: 'check jira issue'
        uses: archaic10/check-existence-jira-issue@v1
        with:
          url-jira:  'https://madeiramadeira.atlassian.net/rest/api/3/issue//SRE-417'
          basic-auth: ${{ secrets.BASIC_AUTH_JIRA }}
        
  check-status-service-desk:
    runs-on: ubuntu-latest
    name: 'check status service desk'
    needs: check-existence-jira-issue 
    steps:
      - name: 'Create GMUD'
        id: res
        run: |
          data=$(curl --location --request POST 'http://kong-wallarm.redekasa.com/slifer/v1/gmud' \
          --header "Authorization: ${{ secrets.BASIC_AUTH_JIRA }}" \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "serviceDeskId": "31",
              "requestTypeId": "538",
              "id_card_issue": "SRE-417",              
              "service": [{"id" : "ari:cloud:graph::service/e27f7002-0a2f-11eb-98e1-0a77f3f45304/907c246a-0f3a-11ec-8fa8-0abe3f4a6601"}],
              "tecnical_approval": "adolfo.pereira@madeiramadeira.com.br",
              "business_approval": "bruno.oliveira@madeiramadeira.com.br"
          }
          ' | jq -r '.data')
                  
          echo "::set-output name=GMUD::${data}"        
          
      - name: 'check status GMUD'
        run: echo ${{ steps.res.outputs.GMUD }}
        
      - uses: actions/checkout@v2
      - id: foo
        uses: archaic10/check-status-service-desk@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url-jira:  ${{ steps.res.outputs.GMUD }}
          basic-auth: ${{ secrets.BASIC_AUTH_JIRA }}
      - name: Get the output foo
        run: echo "${{ steps.foo.outputs.result }}"
