name: GMUD

on:
  pull_request:
    branches:
      - feature/create-gmud
 
jobs:
  check-status-service-desk:
    runs-on: ubuntu-latest
    name: check status service desk
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: archaic10/check-status-service-desk@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path-file: 'gmud.json'
          url-jira: 'https://madeiramadeira.atlassian.net/rest/servicedeskapi/request/CDO-'
          basic-auth: ${{ secrets.BASIC_AUTH_JIRA }}
      - name: Get the output foo
        run: echo "The time was ${{ steps.foo.outputs.result }}"
