on: [push]
name: Test
env:
  MY_NAME: testUser
jobs:
  description_jira:
    runs-on: ubuntu-latest
    steps:
    - name: Pega descrição da tarefa do jira
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://madeiramadeira.atlassian.net/rest/api/2/issue/SRE-310?fields=description'
        method: 'GET'
        username: lucas.villatore@madeiramadeira.com.br
        password: D4vuqvluqUFpp8T1EYNMC4C8
    - name: Mostra na tela a resposta da requisição
      shell: pwsh
      run: echo ${{ steps.myRequest.outputs.response }}