# name: Jira CI
# on:
#   push:
#     branches: [ main ]
# jobs:
#   test-transition-issue:
#       name: Transition Issue
#       runs-on: ubuntu-latest
#       steps:
#       - name: Extract branch name
#         shell: bash
#         run: echo "##[set-output name=branch;]$(echo ${{github.event.pull_request.head.ref}} | awk -F/ '{print $NF}')"
#         id: extract_branch
#       - name: Login
#         uses: atlassian/gajira-login@master
#         env:
#           JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#           JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
#           JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
#           branch_name: ${{github.event.pull_request.head.ref}} 
#       - name: Comment on issue
#         uses: atlassian/gajira-comment@master
#         with:
#           issue: ${{ steps.extract_branch.outputs.branch }}
#           comment: ${{secrets.JIRA_COMMENT_DONE}}
#       - name: Transition issue
#         uses: atlassian/gajira-transition@master
#         with:
#           issue: ${{ steps.extract_branch.outputs.branch }}
#           transition: ${{secrets.JIRA_STEP_DONE}}    