on: [push]
name: Test
env:
  MY_NAME: testUser
jobs:
  description_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node for testing
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm test      
      - name: GET request
        id: request
        uses: satak/webrequest-action@master
        with:
          url: https://madeiramadeira.atlassian.net/rest/api/2/issue/SRE-310?fields=description
          method: GET
          username: lucas.villatore@madeiramadeira.com.br
          password: ${{ secrets.JIRA_API_TOKEN }}
      - name: Get Description
        shell: bash
        run: |
        echo ${{steps.request.outputs.response.description}}