name: Jira CI
on: 
  push:
    branches:
      - main
      - production
      - master
      - feature/github-actions-config
      - SRE-310_teste
jobs:  
  transition-issue:
    name: Branch Issue
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${{github.event.ref}} | awk -F/ '{print $NF}')"
      shell: bash
      id: get_branch_name
    - name: teste
      #echo ${{ steps.get_branch_name.outputs.branch }}
      run:   echo ${{ steps.get_branch_name.outputs.branch }} | awk '{split($0,a,"_"); print a[1]}'
    - name: Extract id jira task
      shell: bash
      run: echo "##[set-output name=jira_task;]$(echo ${{steps.get_branch_name.outputs.branch }} | awk '{split($0,a,"_"); print a[1]}')"