on: [push]
name: Test
env:
  MY_NAME: testUser
jobs:
  description_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      #- name: Setup Node for testing
      #  uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install      
      - name: GET request
        id: request
        #uses: satak/webrequest-action@master
        uses: fjogeleit/http-request-action@master
        with:
          url: https://madeiramadeira.atlassian.net/rest/api/2/issue/SRE-310?fields=description
          method: GET
          username: lucas.villatore@madeiramadeira.com.br
          password: ${{ secrets.JIRA_API_TOKEN }}
          headers:  'accept: application/json'
      - name: Get Description Jira
        shell: pwsh
        run: |
          $output = '${{ steps.request.outputs.response }}' | ConvertFrom-Json
          Write-Host $($output)
      - name: Gerar release
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.github.com/repos/lucasvillatore/git-actions-code-dojo/releases'
          method: 'POST'
          data: '{"tag_name": "pelo action povao","body": "oiie action"}'
          bearerToken: '${{ secrets.GIT_TOKEN }}'
