on: [push]
name: Test
env:
  MY_NAME: testUser
jobs:
  description_jira:
    runs-on: ubuntu-latest
    steps:
    - name: Pega descrição da tarefa do jira
      id: request
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://madeiramadeira.atlassian.net/rest/api/2/issue/SRE-310?fields=description'
        method: 'GET'
        username: ${{ secrets.JIRA_USER_EMAIL }}
        password: ${{ secrets.JIRA_API_TOKEN }}
    - name: Mostra na tela a resposta da requisição
      shell: pwsh
      run: |
        echo ${{toJSON(steps.request.outputs.response) }}