name: Jira CI
on: 
  push:
    branches:
      - main
      - production
      - master
      - feature/github-actions-config
jobs:  
  transition-issue:
    name: Branch Issue
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${{github.event.ref}} | awk -F/ '{print $NF}')"
      shell: bash
      id: get_branch_name
    - name: teste
      run: echo ${{ steps.get_branch_name.outputs.branch }}  
