name: Set release notes from JiraSoftware
on: [push]
jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Get object from JiraSoftware
        id: request
        uses: fjogeleit/http-request-action@master
        with:
        # Pegamos o nome dinamico ele está no arquivo jira_name_branch.yml, agora só precisamos pegar a descrição dinamicamente
          url: https://madeiramadeira.atlassian.net/rest/api/2/issue/SRE-310?fields=description
          method: GET
          username: ${{ secrets.JIRA_USER_EMAIL}}
          password: ${{ secrets.JIRA_API_TOKEN }}
          headers:  'accept: application/json'
      - name: Get description from task on JiraSoftware
        id: jira
        shell: pwsh
        run: |
          $output = '${{ steps.request.outputs.response }}'
          $description = $(echo $output | jq -r '.fields.description')
          echo "::set-output name=DESCRIPTION::$description"
      - name: Generate release notes on GitHub
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.github.com/repos/lucasvillatore/git-actions-code-dojo/releases'
          method: 'POST'
          data: '{"tag_name": "release-2.1.0","body": "${{steps.jira.outputs.DESCRIPTION}}"}'
          bearerToken: '${{ secrets.GIT_TOKEN }}'
