on: [push]
name: Test
env:
  MY_NAME: testUser
jobs:
  webrequest_test:
    runs-on: ubuntu-latest
    name: Test POST and GET web requests
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node for testing
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm test      
      - name: GET request
        id: get-request
        uses: satak/webrequest-action@master
        with:
          url: https://madeiramadeira.atlassian.net/rest/api/2/issue/SRE-310?fields=description
          user: lucas.villatore@madeiramadeira.com.br:${{ secrets.JIRA_API_TOKEN }}
          method: GET
          headers: 'Accept: application/json'
      - name: get-request output
        shell: pwsh
        run: |
          $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
          Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"