name: Node.js CI
on: 
  push:
    branch: 
      - feature/ci

jobs:
  build:
    name: Npm install & build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  teste-unitario: 
    needs: build
    name: Npm unitary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3