name: Node.js CI
on: 
  push:
    branch: 
      - feature/ci

jobs:
  build:
    name: Npm install & build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci #Restore: github action (yaml)
    - run: npm run build --if-present #Build: github action (yaml)

  teste-unitario: 
    needs: build
    name: Npm test & coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3