name: teste

on:
  push:
    branches:
      - feature/test-gmud
   

jobs:
      
  check:
    runs-on: ubuntu-latest
    name: 'teste' 
    steps:   
       - uses: actions/checkout@v2
       - id: foo
         uses: archaic10/validation-deploy@v7
         with:
           url-jira: "https://madeiramadeira.atlassian.net/rest/api/3/issue/PTECH-211"
           basic-auth: ${{ secrets.BASIC_AUTH_JIRA }}
